service: serverless-cms

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    shouldStartNameWithService: true

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: api/sucursales
          method: get
      - http:
          path: api/bannerHero
          method: get 
      - http:
          path: api/configuraciones/home/
          method: get        
      - http:
          path: api/doblePack/{idSucursal}
          method: get
      - http:
          path: api/triplePack/{idSucursal}
          method: get   
      - http:
          path: api/bannerFooter/
          method: get
      - http:
          path: api/fullConnected/
          method: get    
      - http:
          path: api/cardStreaming/
          method: get    
      - http:
          path: api/tv/
          method: get 
      - http:
          path: api/permisosSucursal/
          method: get   
      - http:
          path: api/simetricoSucursal/
          method: get 
      - http:
          path: api/trivias/
          method: get    
      - http:
          path: api/promoEspecialHome/
          method: get    
      - http:
          path: api/xview/{idSucursal}
          method: get 
      - http:
          path: api/extraPromoDisney/
          method: get      
      - http:
          path: api/extraPromoNetflix/
          method: get  
      - http:
          path: api/extraPromoAmazonPrime/
          method: get  
      - http:
          path: api/triviaspreguntas/data/{id}
          method: get    
      - http:
          path: api/trivias/data/{id}
          method: get 
      - http:
          path: api/respuestas/
          method: post        
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3000